### ISSUE TITLE
Level issue

### ISSUE THREAD

**Issue by dreadedkillerz** [adefee/paver-palworld-save-editor#8]

**Comment by adefee** [comment]
looks like you removed your initial comment, but it was about exp. If you don't specify XP, Paver will calculate it for you based on the level you specify. If you specify an exp field, Paver will trust you know what you're doing and use that instead. This also means if you find an issue or don't like what Paver has calculated, you can manually adjust the value to whatever you want, too.

since you removed the comment, i'm assuming you figured out this out from trial/error or the docs, will close this. Please reopen the issue if you're still having this problem. Sorry I didn't see sooner!
